### PR TITLE
feat: login this extension through casdoor

### PR DESCRIPTION
**Pull request by wenxuan70**
reference docs:
[Casdoor OAuth2.0](https://casdoor.org/docs/how-to-connect/oauth#implicit-grant)
[Non-Google account authentication](https://developer.chrome.com/docs/apps/app_identity/#non)

### CODE REVIEW

**Comment by Resulte** [comment]
@wenxuan70  It seems that your application only displays the login page when the chrome extension is installed. But if the users logout or want to change account after the chrome extension is installed, how can they find the login page? How about show the login button on the extension pane?

**Comment by wenxuan70** [comment]
@Resulte Now this extension adds a logout function and uses a popup page to log in and log out.

**Comment by Resulte** [comment]
@wenxuan70 Please rebase firstly. And plz update `README.md`. It would be great if you could attach a demo video.

**Comment by wenxuan70** [comment]
https://user-images.githubusercontent.com/55948263/183442823-d3010281-c2a2-4f59-a258-1ca4704b35a6.mp4

**Comment by hsluoyz** [comment]
@wenxuan70 the demo looks good!

@Resulte plz review the code

**Comment by hsluoyz** [comment]
@wenxuan70 plz modify

**Review by Resulte — APPROVED** [review]

**Pull request merged**
